const DESTINATIONS = [
  {id:'santorini',name:'Santorini',country:'Greece',continent:'Europe',type:'Relaxation',budget:'High',
    image:'images/santorini.jpg', // Changed from URL to local path
    description:'Whitewashed cliffside villages, cobalt-blue domes, and unforgettable Aegean sunsets define this iconic Cycladic island.',
    attractions:['Oia Sunset Point','Red Beach','Akrotiri Archaeological Site','Caldera Cruise','Fira Cable Car'],
    costs:[{cat:'Budget Stay',price:'$80/night'},{cat:'Mid-range Hotel',price:'$220/night'},{cat:'Luxury Resort',price:'$650/night'},{cat:'Avg. Meal',price:'$35'},{cat:'Daily Transport',price:'$25'}]},
  {id:'kyoto',name:'Kyoto',country:'Japan',continent:'Asia',type:'Cultural',budget:'Medium',
    image:'images/kyoto.jpg',
    description:'Japan’s former imperial capital — a city of ancient temples, geisha districts, bamboo groves, and exquisite tea ceremonies.',
    attractions:['Fushimi Inari Shrine','Arashiyama Bamboo Grove','Kinkaku-ji (Golden Pavilion)','Gion District','Kiyomizu-dera'],
    costs:[{cat:'Hostel',price:'$30/night'},{cat:'Ryokan',price:'$180/night'},{cat:'Luxury Ryokan',price:'$500/night'},{cat:'Avg. Meal',price:'$15'},{cat:'Daily Transit',price:'$10'}]},
  {id:'bali',name:'Bali',country:'Indonesia',continent:'Asia',type:'Relaxation',budget:'Low',
    image:'images/bali.jpg',
    description:'A tropical paradise of emerald rice terraces, sacred temples, world-class surf, and a serene spiritual atmosphere.',
    attractions:['Tegallalang Rice Terraces','Uluwatu Temple','Mount Batur Sunrise Hike','Ubud Monkey Forest','Nusa Penida'],
    costs:[{cat:'Hostel',price:'$12/night'},{cat:'Boutique Villa',price:'$70/night'},{cat:'Luxury Villa',price:'$300/night'},{cat:'Avg. Meal',price:'$6'},{cat:'Scooter Rental',price:'$7/day'}]},
  {id:'patagonia',name:'Patagonia',country:'Argentina',continent:'South America',type:'Adventure',budget:'Medium',
    image:'images/patagonia.jpg',
    description:'Wild, untamed wilderness of jagged peaks, blue glaciers, and windswept steppes at the southern tip of the Americas.',
    attractions:['Perito Moreno Glacier','Torres del Paine Trek','Fitz Roy Hike','Tierra del Fuego','El Chaltén'],
    costs:[{cat:'Refugio',price:'$40/night'},{cat:'Mountain Lodge',price:'$160/night'},{cat:'Luxury Estancia',price:'$500/night'},{cat:'Avg. Meal',price:'$20'},{cat:'Guide/day',price:'$80'}]},
  {id:'iceland',name:'Reykjavik',country:'Iceland',continent:'Europe',type:'Nature',budget:'High',
    image:'images/iceland.jpg',
    description:'Land of fire and ice — geothermal lagoons, dramatic waterfalls, volcanic landscapes, and the magical Northern Lights.',
    attractions:['Blue Lagoon','Golden Circle','Northern Lights Tour','Jökulsárlón Glacier Lagoon','Reynisfjara Beach'],
    costs:[{cat:'Hostel',price:'$55/night'},{cat:'Mid Hotel',price:'$250/night'},{cat:'Luxury',price:'$600/night'},{cat:'Avg. Meal',price:'$45'},{cat:'Car Rental',price:'$80/day'}]},
  {id:'marrakech',name:'Marrakech',country:'Morocco',continent:'Africa',type:'Cultural',budget:'Low',
    image:'images/marrakech.jpg',
    description:'A maze of vibrant souks, intricate riads, fragrant spice markets, and the lively Jemaa el-Fnaa square at sunset.',
    attractions:['Jemaa el-Fnaa','Majorelle Garden','Bahia Palace','Atlas Mountains Day Trip','Medina Souks'],
    costs:[{cat:'Riad Budget',price:'$25/night'},{cat:'Mid Riad',price:'$90/night'},{cat:'Luxury Riad',price:'$300/night'},{cat:'Avg. Meal',price:'$10'},{cat:'Taxi',price:'$5'}]},
  {id:'queenstown',name:'Queenstown',country:'New Zealand',continent:'Oceania',type:'Adventure',budget:'High',
    image:'images/queenstown.jpg',
    description:'The adventure capital of the world — bungee jumping, jet boats, alpine hikes, and stunning lakeside scenery.',
    attractions:['Skyline Gondola','Kawarau Bungy','Milford Sound Day Trip','Shotover Jet','Lake Wakatipu Cruise'],
    costs:[{cat:'Hostel',price:'$40/night'},{cat:'Mid Lodge',price:'$200/night'},{cat:'Luxury',price:'$550/night'},{cat:'Avg. Meal',price:'$28'},{cat:'Activity Avg.',price:'$120'}]},
  {id:'banff',name:'Banff',country:'Canada',continent:'North America',type:'Nature',budget:'Medium',
    image:'images/banff.jpg',
    description:'Turquoise alpine lakes, towering Rocky Mountain peaks, and pristine wilderness in Canada’s oldest national park.',
    attractions:['Lake Louise','Moraine Lake','Banff Gondola','Johnston Canyon','Icefields Parkway'],
    costs:[{cat:'Hostel',price:'$45/night'},{cat:'Mid Hotel',price:'$200/night'},{cat:'Fairmont',price:'$700/night'},{cat:'Avg. Meal',price:'$30'},{cat:'Park Pass',price:'$10/day'}]},
  {id:'cairo',name:'Cairo',country:'Egypt',continent:'Africa',type:'Cultural',budget:'Low',
    image:'images/cairo.jpg',
    description:'Where ancient wonders meet modern chaos — the pyramids, the Nile, and millennia of pharaonic history.',
    attractions:['Pyramids of Giza','Egyptian Museum','Khan el-Khalili','Nile Felucca Ride','Coptic Cairo'],
    costs:[{cat:'Budget Hotel',price:'$20/night'},{cat:'Mid Hotel',price:'$80/night'},{cat:'Luxury Nile View',price:'$250/night'},{cat:'Avg. Meal',price:'$8'},{cat:'Taxi',price:'$4'}]},
  {id:'rio',name:'Rio de Janeiro',country:'Brazil',continent:'South America',type:'Relaxation',budget:'Medium',
    image:'images/rio.jpg',
    description:'Sun-soaked beaches, samba rhythms, dramatic mountain backdrops, and the iconic Christ the Redeemer statue.',
    attractions:['Christ the Redeemer','Sugarloaf Mountain','Copacabana Beach','Ipanema','Tijuca Forest'],
    costs:[{cat:'Hostel',price:'$20/night'},{cat:'Mid Hotel',price:'$110/night'},{cat:'Luxury',price:'$400/night'},{cat:'Avg. Meal',price:'$18'},{cat:'Uber',price:'$8'}]},
  {id:'swissalps',name:'Swiss Alps',country:'Switzerland',continent:'Europe',type:'Adventure',budget:'High',
    image:'images/swissalps.jpg',
    description:'Postcard-perfect peaks, glacier expresses, charming mountain villages, and world-class skiing and hiking.',
    attractions:['Matterhorn','Jungfraujoch','Glacier Express','Lake Lucerne','Zermatt Village'],
    costs:[{cat:'Hostel',price:'$60/night'},{cat:'Mid Hotel',price:'$280/night'},{cat:'Luxury Chalet',price:'$800/night'},{cat:'Avg. Meal',price:'$40'},{cat:'Rail Pass',price:'$70/day'}]},
  {id:'maldives',name:'Maldives',country:'Maldives',continent:'Asia',type:'Relaxation',budget:'High',
    image:'images/maldives.jpg',
    description:'Crystal-clear lagoons, overwater bungalows, vibrant coral reefs, and the ultimate barefoot luxury experience.',
    attractions:['Overwater Villas','Reef Snorkeling','Sandbank Picnics','Sunset Dolphin Cruise','Spa Retreats'],
    costs:[{cat:'Guesthouse',price:'$80/night'},{cat:'Resort',price:'$500/night'},{cat:'Overwater Villa',price:'$1200/night'},{cat:'Avg. Meal',price:'$50'},{cat:'Speedboat',price:'$100'}]}
];

const HERO_SLIDES = [
  {img:'images/hero1.jpg',quote:'The world is a book, and those who do not travel read only one page.',author:'Saint Augustine'},
  {img:'images/hero2.jpg',quote:'Travel far enough, you meet yourself.',author:'David Mitchell'},
  {img:'images/hero3.jpg',quote:'Adventure is worthwhile.',author:'Aesop'},
  {img:'images/hero4.jpg',quote:'Not all those who wander are lost.',author:'J.R.R. Tolkien'}
];
